### PR TITLE
feat : added image, rating and text-utills

### PR DESCRIPTION
**Pull request by Prashantrajput11**
Added :
* Image : Round and responsive image
* Rating
* Text utilities : Text-Transform, Headings and alignment

image
image
image
image

image

### CODE REVIEW

**Review by JaswanthReddyPadala — APPROVED** [review]
UI Could be better. But Code looks good.
U can proceed further, All the Best ✅

**Review by Shrinkhlarajpoot — APPROVED** [review]

**Comment by Shrinkhlarajpoot** [comment]
Clean code...Can work on UI side if you wish

**Comment by Prashantrajput11** [comment]
> Clean code...Can work on UI side if you wish

Thanks. Will definitely work on the UI Part

**Comment by Prashantrajput11** [comment]
> UI Could be better. But Code looks good. U can proceed further, All the Best ✅

Thanks. Will work on the UI part

**Pull request merged**
